-- Compare ACCOUNT and ENTITY columns
SELECT DISTINCT  [YEAR]
      ,[SCENARIO]
      ,[VERSION]
      ,[DATA]
      ,[CURRENCY]
      ,[ACCOUNT]
      ,[ENTITY]
      ,[CUSTOMER]
      ,[PRODUCT]
      ,[PRODUCT_TYPE]
      ,[SITE]
      ,[CUSTOM1]
      ,[CUSTOM2]
      ,[CUSTOM3]
      ,[CREATE_DATE],'ACCOUNT' AS ColumnType,ACCOUNT AS 'VALUE','COST_CENTER_ACTUAL' AS SOURCE
FROM [BSDB].ODS.COST_CENTER_ACTUAL
LEFT JOIN [BSDB].[dbo].[V_IECPLN_ACCOUNT]
ON ACCOUNT COLLATE Chinese_Taiwan_Stroke_CI_AS = MemberName
WHERE MemberName IS NULL

UNION ALL

SELECT DISTINCT [YEAR]
      ,[SCENARIO]
      ,[VERSION]
      ,[DATA]
      ,[CURRENCY]
      ,[ACCOUNT]
      ,[ENTITY]
      ,[CUSTOMER]
      ,[PRODUCT]
      ,[PRODUCT_TYPE]
      ,[SITE]
      ,[CUSTOM1]
      ,[CUSTOM2]
      ,[CUSTOM3]
      ,[CREATE_DATE], 'ENTITY' AS ColumnType, ENTITY AS 'VALUE','COST_CENTER_ACTUAL' AS SOURCE
FROM [BSDB].ODS.COST_CENTER_ACTUAL
LEFT JOIN [BSDB].[dbo].[V_IECPLN_ENTITY]
ON ENTITY COLLATE Chinese_Taiwan_Stroke_CI_AS = MemberName
WHERE MemberName IS NULL

UNION ALL
SELECT DISTINCT  [YEAR]
      ,[SCENARIO]
      ,[VERSION]
      ,[DATA]
      ,[CURRENCY]
      ,[ACCOUNT]
      ,[ENTITY]
      ,[CUSTOMER]
      ,[PRODUCT]
      ,[PRODUCT_TYPE]
      ,[SITE]
      ,[CUSTOM1]
      ,[CUSTOM2]
      ,[CUSTOM3]
      ,[CREATE_DATE], 'ACCOUNT' AS ColumnType,ACCOUNT AS 'VALUE','ASSETS_DEPRECIATION_BUDGET' AS SOURCE
FROM [BSDB].ODS.ASSETS_DEPRECIATION_BUDGET
LEFT JOIN [BSDB].[dbo].[V_IECPLN_ACCOUNT]
ON ACCOUNT COLLATE Chinese_Taiwan_Stroke_CI_AS = MemberName
WHERE MemberName IS NULL

UNION ALL

SELECT DISTINCT  [YEAR]
      ,[SCENARIO]
      ,[VERSION]
      ,[DATA]
      ,[CURRENCY]
      ,[ACCOUNT]
      ,[ENTITY]
      ,[CUSTOMER]
      ,[PRODUCT]
      ,[PRODUCT_TYPE]
      ,[SITE]
      ,[CUSTOM1]
      ,[CUSTOM2]
      ,[CUSTOM3]
      ,[CREATE_DATE], 'ENTITY' AS ColumnType, ENTITY AS 'VALUE','ASSETS_DEPRECIATION_BUDGET' AS SOURCE
FROM [BSDB].ODS.ASSETS_DEPRECIATION_BUDGET
LEFT JOIN [BSDB].[dbo].[V_IECPLN_ENTITY]
ON ENTITY COLLATE Chinese_Taiwan_Stroke_CI_AS = MemberName
WHERE MemberName IS NULL

UNION ALL
SELECT DISTINCT  [YEAR]
      ,[SCENARIO]
      ,[VERSION]
      ,[DATA]
      ,[CURRENCY]
      ,[ACCOUNT]
      ,[ENTITY]
      ,[CUSTOMER]
      ,[PRODUCT]
      ,[PRODUCT_TYPE]
      ,[SITE]
      ,[CUSTOM1]
      ,[CUSTOM2]
      ,[CUSTOM3]
      ,[CREATE_DATE], 'ACCOUNT' AS ColumnType,ACCOUNT AS 'VALUE','ASSETS_DEPRECIATION_ROLLING' AS SOURCE
FROM [BSDB].ODS.ASSETS_DEPRECIATION_ROLLING
LEFT JOIN [BSDB].[dbo].[V_IECPLN_ACCOUNT]
ON ACCOUNT COLLATE Chinese_Taiwan_Stroke_CI_AS = MemberName
WHERE MemberName IS NULL

UNION ALL

SELECT DISTINCT  [YEAR]
      ,[SCENARIO]
      ,[VERSION]
      ,[DATA]
      ,[CURRENCY]
      ,[ACCOUNT]
      ,[ENTITY]
      ,[CUSTOMER]
      ,[PRODUCT]
      ,[PRODUCT_TYPE]
      ,[SITE]
      ,[CUSTOM1]
      ,[CUSTOM2]
      ,[CUSTOM3]
      ,[CREATE_DATE], 'ENTITY' AS ColumnType, ENTITY AS 'VALUE','ASSETS_DEPRECIATION_ROLLING' AS SOURCE
FROM [BSDB].ODS.ASSETS_DEPRECIATION_ROLLING
LEFT JOIN [BSDB].[dbo].[V_IECPLN_ENTITY]
ON ENTITY COLLATE Chinese_Taiwan_Stroke_CI_AS = MemberName
WHERE MemberName IS NULL

ORDER BY VALUE,SOURCE