SELECT [YEAR]
      ,[VERSION]
      ,[SCENARIO]
      ,[DATA]
      ,[CURRENCY]
      ,[ACCOUNT]
      ,[ENTITY]
      ,[SITE]
      ,[CUSTOM1]
      ,[CUSTOM2]
      ,[CUSTOM3]
     ,[JAN]
      ,[FEB]
      ,[MAR]
      ,[APR]
      ,[MAY]
      ,[JUN]
      ,[JUL]
      ,[AUG]
      ,[SEP]
      ,[OCT]
      ,[NOV]
      ,[DEC]
      ,[IS_NEW_FA_DEDUCTION] FROM [ODS].[FA_AMOUNT_ROLLING] WHERE [YEAR] = 'FY24' AND [IS_NEW_FA_DEDUCTION] = 'N'