SELECT YEAR, 'Plan1' AS CUBE, YEAR + ',' + PERIOD + ',' + 'Budget SAP' + ',' + VERSION + ',' + DATA + ',' + CURRENCY + ',' + ENTITY + ',' + SITE + ',' + CUSTOM1 + ',' + CUSTOM3 AS POV, CUSTOM2, PROJ_DESC, CONTR_AREA, DEPT_CD, DIVISION, LOCAL_CUR, BUD_TTL, BUD_USED, BUD_REMAIN, OWNER_ID, OWNER_NAME, BUD_TYPE
FROM   ODS.FA_INFO_ROLLING
WHERE (IS_NEW_FA_DEDUCTION = 'N')
order by CUSTOM2